name: "Update API Docs and Create PR"

on:
  push:
    branches:
      - main  # Adjust this branch based on your main branch name

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate or Update Documents
        run: |
          echo "Starting this part 1"

      - name: Create directories
        run: "mkdir -p packages/docs/apis"

      - name: Create Lorem Ipsum JSON file
        run: |
          echo '{"content": "Lorem ipsum dolor sit amet, consecascascasscasavsvavetetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."}' > packages/docs/apis/lorem_ipsum.json

      - name: Print GitHub Token
        run: |
          echo "GitHub Token: ${{ secrets.GH_TOKEN }}"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add or update API docs [skip ci]"

      - name: Remove Existing Remote
        run: |
          echo "Starting this part 7"
          REMOTE_NAME="other_repo"
        
          if git remote get-url $REMOTE_NAME >/dev/null 2>&1; then
            echo "Removing existing remote"
            git remote remove $REMOTE_NAME
          fi

      - name: Push Changes
        run: |
          echo "Starting this part 1"
          git clone https://${{ secrets.GH_TOKEN }}@github.com/jamesnsinclair/pern-todo clonedFolder || true
          echo "Starting this part 2"
          mkdir -p clonedFolder/packages/docs/apis
          cp -r packages/docs/apis/* clonedFolder/packages/docs/apis/ -f
          cd clonedFolder
          git add .
          git commit -m "this is a test"
          git push
          
          echo "Starting this part 3"
          PR_BRANCH="update-api-docs-$(date +%s)"
          git checkout -b $PR_BRANCH
          git push -u origin $PR_BRANCH
          
          echo "Starting this part 4"
          PR_TITLE="Update API Docs"
          PR_BODY="This PR updates the API documentation."
          PR_BASE_BRANCH="main"  # Change this to your main branch name
          PR_HEAD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          echo "Starting this part 5"
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$PR_HEAD_BRANCH\",\"base\":\"$PR_BASE_BRANCH\"}" "https://api.github.com/repos/jamesnsinclair/pern-todo/pulls"
        
