on:
  push:
    branches:
      - main  # Adjust this branch based on your main branch name

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Create Temporary Folder
        run: mkdir api-docs-temp

      - name: Move Schema Files to Temporary Folder
        run: |
          mv docs/schema/index.md api-docs-temp/  || true
          mv /schema-graphql* api-docs-temp/ || true

      - name: Check for Changes
        id: check_changes
        run: |
          current_directory=$(pwd)
          project_name=$(basename "$current_directory")
          remote_changes=$(git ls-remote --exit-code https://${{ secrets.GH_TOKEN }}@github.com/jamesnsinclair/pern-todo.git $project_name/main && echo "true" || echo "false")
          if [ "$remote_changes" == "true" ]; then
            echo "::set-output name=changes::true"
          fi

      - name: Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          current_directory=$(pwd)
          project_name=$(basename "$current_directory")
          echo "Project Name: $project_name"
        
          git clone https://${{ secrets.GH_TOKEN }}@github.com/jamesnsinclair/pern-todo clonedFolder || true
          
          # Check if the destination folder exists, and create it if not
          destination_folder="clonedFolder/packages/docs/graphql-api/$project_name"
          if [ ! -d "$destination_folder" ]; then
              mkdir -p "$destination_folder"
          fi
          # Copy files from api-docs-temp to the destination folder
          cp -r api-docs-temp/* "$destination_folder" -f || true
          cd clonedFolder
          git add .
          git commit -m "This is a test"
          git push
          PR_BRANCH="update-api-docs-$(date +%s)"
          git checkout -b $PR_BRANCH
          git push -u origin $PR_BRANCH
          
          PR_TITLE="Update API Docs"
          PR_BODY="This PR updates the API documentation."
          PR_BASE_BRANCH="main"  # Change this to your main branch name
          PR_HEAD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$PR_HEAD_BRANCH\",\"base\":\"$PR_BASE_BRANCH\"}" "https://api.github.com/repos/jamesnsinclair/pern-todo/pulls"

      - name: Move Files Back to Original Locations
        run: |
          mkdir -p packages/docs/graphql-api/schema/
          mv api-docs-temp/* packages/docs/graphql-api/schema/ || true
